# -*- coding: utf-8 -*-
"""Desenvolvimento_TCCII.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QFg9V6HgmOLxZGRlDDNV_aOp9sUnSGGN
"""

from google.colab import drive
drive.mount ('/content/drive')

import pandas as pd
import numpy as np

import statsmodels.api as sm #módulo que fornece classes e funções para realização de testes estatísticos diferentes e exploração de dados estatísticos.
import matplotlib.pyplot as plt #módulo para criação de graficos

dados = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/BD/dataset.csv')
dados.head(10)

dados.info

dados.dtypes

tipos_dados = pd.DataFrame(dados.dtypes, columns = ['Tipos de dados'])
tipos_dados.columns.name = 'Variaveis'
tipos_dados

dados.shape

x = np.array ([dados.n_reviews])
y = np.array ([dados.price])

correlacao = np.corrcoef(0,1)
#x = x.reshape(-1,1)
from sklearn.linear_model import LinearRegression
regressao = LinearRegression()
regressao.fit

regressao.coef_
regressao.intercept_

print(f"regressao.coef_ {regressao.coef_}")
print(f"regressao.intercept_ {regressao.intercept_}")
print(regressao.predict(x))

previsao = regressao.predict(np.array(30).reshape(1,1))
print(str(previsao[0]))